<?php

namespace NAO\UserBundle\Repository;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function filtrerUtilisateurs($recherche)
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.firstname LIKE :recherche')
            ->orWhere('u.lastname LIKE :recherche')
            ->orWhere('u.username LIKE :recherche')
            ->orWhere('u.email LIKE :recherche')
            ->setParameter('recherche', $recherche)
            ->getQuery();

        return $query->getArrayResult();

    }

    public function findAll()
    {
        return $this->findBy(array(), array('lastname' => 'ASC', 'firstname' => 'ASC', 'username' => 'ASC'));
    }
}
